### ISSUE TITLE
Upload gulp tasks returns Forbidden error

### ISSUE THREAD

**Issue by vivanov1410** [connio/emails#17]
```
Error: S3 headObject Error: Forbidden: null
```

**Comment by vivanov1410** [comment]
@iangelov I just tested images/avatar uploading on app.connio.net and its not working too (site was not updated). Something is wrong with either amazon or our current credentials. Maybe this will be helpful to you.

**Comment by iangelov** [comment]
I think that it's an intermittent problem with AWS - I've just been able to upload the images assets 3 times:

>~/emails$ gulp upload
[09:31:20] Using gulpfile ~/emails/gulpfile.js
[09:31:20] Starting 'upload'...
[09:31:20] Finished 'upload' after 21 ms
~/emails$ gulp upload
[09:32:27] Using gulpfile ~/emails/gulpfile.js
[09:32:27] Starting 'upload'...
[09:32:27] Finished 'upload' after 23 ms
~/emails$ gulp upload
[09:33:35] Using gulpfile ~/emails/gulpfile.js
[09:33:35] Starting 'upload'...
[09:33:35] Finished 'upload' after 30 ms

**Comment by vivanov1410** [comment]
Looks like its fixed now after Ivan regenerated AWS keys. Closing.

**Comment by iangelov** [comment]
A bit more detail on that, since it's good not to forget - looks like authentication is performed differently with the original keypair. I was able to query the bucket just fine without changing the region from eu-central-1 (S3 namespace is global), but I wasn't able to do that when querying against the us-east-1 endpoint (got a signature-related error). Eu-central-1 is using v4 only, so it might be that it's not working with the older authorization API version.
