### ISSUE TITLE
Test email templates with Litmus

### ISSUE THREAD

**Issue by vivanov1410** [connio/emails#19]

**Comment by Kerthara** [comment]
### Test results

#### reset-password-email
![reset-password-email](https://cloud.githubusercontent.com/assets/6184057/9213073/8eb6a014-4043-11e5-9c88-620ece74bf32.jpg)
**result**: all tests passed

#### verify-account-email
![verify-account-email](https://cloud.githubusercontent.com/assets/6184057/9213084/ab4fea14-4043-11e5-87fe-ca0725f9617d.jpg)
**result**: 
> notes: 
- in iPhone 5s ios7 - picture are not displaying because of glitch in Litmus, same works for reset password email.

#### accept-invitation-email
![accept-invitation-email](https://cloud.githubusercontent.com/assets/6184057/9213090/be81cd78-4043-11e5-8cd3-7d0a10174bc8.jpg)
**result**: 
> notes: 
- in iPhone 5s ios7 - picture are not displaying because of glitch in Litmus, same works for reset password email.

> **bugs**:
- [ ] outlook 2010 / 2013 bg image not centered
